
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 20 00:20:53 ICT 2017
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPAREN = 6;
  public static final int error = 1;
  public static final int PLUS = 2;
  public static final int NUMBER = 7;
  public static final int EXPO = 4;
  public static final int LPAREN = 5;
  public static final int TIMES = 3;
  public static final int EOF = 0;
}

